apiVersion: v1
kind: Service
metadata:
  namespace: rw
  labels:
    name: {name}-preproduction
  name: {name}-preproduction
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    name: {name}-preproduction
