apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: redis
        image: redis
        ports:
         - containerPort: 6379
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "1Gi"
        env:
          - name: SECRET
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_SECRET
          - name: USERNAME
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_USERNAME
          - name: PASSWORD
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_PASSWORD
          - name: REDIS_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI

        ports:
          - containerPort: 3000
      restartPolicy: Always
