apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: rw
  name: {name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {name}
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50
